version: "3"

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE : ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST : ${MYSQL_ROOT_HOST}
      TZ: 'Asia/Seoul'
    ports:   # 테스트 환경을 위해 열어놔야함
      - 3306:3306
    env_file:
      - /home/ubuntu/config/.env
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql # 앞: 로컬 / 뒤: mysql 이미지 공식 문서
    networks:
      - marrymo_net

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass leon0115
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - /home/ubuntu/config/.env
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data # 앞: 로컬 / 뒤 : redis 이미지 공식 문서
    networks:
      - marrymo_net


  marrymo-app:
    container_name: marrymo-app
    image: jaeyun1650/marrymo_be
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}
    ports:
      - 8080:8080
    env_file:
      - /home/ubuntu/config/.env
    depends_on:
      - mysql
      - redis

    networks:
      - marrymo_net


networks:
  marrymo_net:
    external: true
